#!/usr/bin/env python3
"""Emit peload/win32_arity.h: the stdcall argument-byte count per Win32 export.

An i386 stdcall callee pops its own arguments, so a stub standing in for an
import we have not implemented cannot just `ret` -- it has to `ret N` with the
same N the real export uses, or the guest's stack drifts 4 bytes per argument
until some later `ret` jumps into nothing. (x86-64 has no equivalent hazard: the
caller always cleans up, which is why the 64-bit loader never needed this.)

mingw-w64's i686 import libraries carry that N in the decorated symbol name
(_CreateFileW@28), so the numbers here are the real ones rather than a guess.
"""
import os, re, subprocess, sys

LIBDIR = "/usr/i686-w64-mingw32/lib"
OUT    = os.path.join(os.path.dirname(__file__), "..", "peload", "win32_arity.h")

# Every DLL the plugins here import, plus the neighbours a Windows audio plugin
# plausibly reaches for. Scoping the list keeps the generated header to a
# sensible size, and nothing is silently lost: a name the table does not cover
# makes the loader print "unknown stdcall arity" for that import at load time.
DLLS = """
    kernel32 user32 gdi32 shell32 shlwapi ole32 oleaut32 comctl32 comdlg32
    advapi32 wininet winmm msimg32 version msacm32 winspool imm32 uxtheme
    dwmapi ntdll psapi userenv setupapi ws2_32 crypt32 gdiplus
""".split()


def nm(path):
    for tool in ("i686-w64-mingw32-nm", "nm"):
        try:
            return subprocess.run([tool, "--defined-only", path],
                                  capture_output=True, text=True).stdout
        except FileNotFoundError:
            continue
    sys.exit("no nm available")


def main():
    libs = [os.path.join(LIBDIR, "lib%s.a" % d) for d in DLLS]
    absent = [l for l in libs if not os.path.exists(l)]
    if absent:
        print("note: no import library for %s"
              % ", ".join(os.path.basename(a)[3:-2] for a in absent))

    arity = {}
    for lib in sorted(l for l in libs if os.path.exists(l)):
        for m in re.finditer(r'\b_?([A-Za-z_][A-Za-z0-9_]*)@(\d+)\b', nm(lib)):
            name, n = m.group(1), int(m.group(2))
            # A name should not disagree across libraries. If it does, keep the
            # larger count: popping too much is caught loudly on the next call,
            # popping too little drifts quietly.
            arity[name] = max(arity.get(name, 0), n)

    rows = sorted(arity.items())
    with open(OUT, "w") as f:
        f.write("/* Generated by tools/gen_arity.py from the mingw-w64 i686 import\n"
                " * libraries -- do not edit. Maps a Win32 export to the number of\n"
                " * argument bytes its stdcall form pops, so an i386 stub can `ret N`.\n"
                " */\n"
                "#ifndef PELOAD_WIN32_ARITY_H\n#define PELOAD_WIN32_ARITY_H\n\n"
                "typedef struct { const char *sym; unsigned short bytes; } win32_arity;\n\n"
                "/* sorted by name for a binary search */\n"
                "static const win32_arity g_win32_arity[] = {\n")
        for name, n in rows:
            f.write('    { "%s", %d },\n' % (name, n))
        f.write("};\n"
                "#define WIN32_ARITY_N ((int)(sizeof g_win32_arity / sizeof *g_win32_arity))\n\n"
                "/* -1 when the name is unknown, so the caller can say so out loud */\n"
                "static int win32_arity_of(const char *sym)\n"
                "{\n"
                "    int lo = 0, hi = WIN32_ARITY_N - 1;\n"
                "    while (lo <= hi) {\n"
                "        int mid = (lo + hi) / 2, c = strcmp(g_win32_arity[mid].sym, sym);\n"
                "        if (c == 0) return g_win32_arity[mid].bytes;\n"
                "        if (c < 0) lo = mid + 1; else hi = mid - 1;\n"
                "    }\n"
                "    return -1;\n"
                "}\n\n#endif /* PELOAD_WIN32_ARITY_H */\n")
    print("wrote %s: %d exports from %d libraries"
          % (os.path.normpath(OUT), len(rows), len(libs) - len(absent)))


main()
